
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace kp
{

using System;
    using System.Collections.Generic;
    
public partial class Customer
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Customer()
    {

        this.TravelPackages = new HashSet<TravelPackage>();

    }


    public int CustomerID { get; set; }

    public string CustomerName { get; set; }

    public string CustomerSurname { get; set; }

    public string CustomerMiddleName { get; set; }

    public int PassportNumber { get; set; }

    public string PhoneNumber { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TravelPackage> TravelPackages { get; set; }

    public virtual User User { get; set; }

}

}
