
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace kp
{

using System;
    using System.Collections.Generic;
    
public partial class TravelPackage
{

    public int TravelPackageID { get; set; }

    public int TourID { get; set; }

    public int CustomerID { get; set; }



    public virtual Customer Customer { get; set; }

    public virtual Tour Tour { get; set; }

}

}
